# Generated by Django 6.0.5 on 2026-05-17 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Air Jordan 1 Retro', max_length=200)),
                ('descricao', models.TextField(help_text='Detalhes do tênis (material, cor, etc.)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_ativo', models.BooleanField(default=True)),
                ('marca', models.CharField(help_text='Ex: Nike, Adidas, Puma', max_length=50)),
                ('tamanho', models.CharField(help_text='Ex: 39, 40, 41', max_length=5)),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenis_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('UN', 'Unitária (Par)'), ('AT', 'Atacado (Caixa com 12)'), ('EN', 'Encomenda (Importação)')], default='UN', max_length=2)),
                ('condicoes_pagamento', models.CharField(help_text='Ex: PIX com 10% OFF, Cartão em até 12x', max_length=200)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_venda', to='app.produto')),
            ],
        ),
    ]
