# Generated by Django 6.0.5 on 2026-05-19 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto_formavenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titular', models.CharField(max_length=100)),
                ('ultimos_digitos', models.CharField(max_length=4)),
                ('bandeira', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('elo', 'Elo'), ('amex', 'American Express'), ('hipercard', 'Hipercard')], max_length=20)),
                ('validade_mes', models.PositiveSmallIntegerField()),
                ('validade_ano', models.PositiveSmallIntegerField()),
                ('principal', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
