# Generated by Django 6.0.5 on 2026-05-19 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cartaocredito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaocredito',
            options={'verbose_name': 'Cartão de Crédito', 'verbose_name_plural': 'Cartões de Crédito'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('33', '33'), ('33.5', '33,5'), ('34', '34'), ('34.5', '34,5'), ('35', '35'), ('35.5', '35,5'), ('36', '36'), ('36.5', '36,5'), ('37', '37'), ('37.5', '37,5'), ('38', '38'), ('38.5', '38,5'), ('39', '39'), ('39.5', '39,5'), ('40', '40'), ('40.5', '40,5'), ('41', '41'), ('41.5', '41,5'), ('42', '42'), ('42.5', '42,5'), ('43', '43'), ('43.5', '43,5'), ('44', '44'), ('44.5', '44,5'), ('45', '45'), ('45.5', '45,5'), ('46', '46'), ('46.5', '46,5')], max_length=4)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='app.produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'unique_together': {('produto', 'tamanho')},
            },
        ),
    ]
