# Generated by Django 6.0.5 on 2026-05-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cartaocredito_options_alter_endereco_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
    ]
