# Generated by Django 6.0.5 on 2026-05-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_produto_tamanho'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='estoque',
            constraint=models.UniqueConstraint(fields=('produto', 'tamanho'), name='estoque_produto_tamanho_unico'),
        ),
    ]
