# Generated by Django 6.0.5 on 2026-05-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='endereco',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('usuario',), name='unique_endereco_principal_por_usuario'),
        ),
    ]
