# Generated by Django 6.0.5 on 2026-06-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_endereco_unique_endereco_principal_por_usuario'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartaocredito',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('usuario',), name='unique_cartao_principal_por_usuario'),
        ),
    ]
